// Converts data/species_data.json (the source of truth) into a SQL seed file
// for the Supabase schema in supabase/migrations/. Run after any edit to
// species_data.json (e.g. via scripts/reimport_from_excel.py) to keep the
// Supabase copy in sync:
//
//   node scripts/generate_supabase_seed.mjs
//
// Then apply supabase/seed/species_seed.sql via `supabase db execute` or the
// SQL editor in the Supabase dashboard.

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, '..');

const data = JSON.parse(
  readFileSync(path.join(root, 'data', 'species_data.json'), 'utf-8')
);

// Known real-world exceptions the rule engine can't derive on its own.
// Kept here (not in species_data.json) because it mirrors
// SPECIES_PAIR_OVERRIDES in app/index.html, which is the current source of
// truth for this table until it's fully moved into the data pipeline.
const PAIR_OVERRIDES = [
  {
    a: 'betta',
    b: 'corydoras',
    result: 'caution',
    reason:
      '베타는 하층에서 조용히 지내는 코리도라스는 대체로 무시하는 편이라 실제로 널리 쓰이는 조합입니다. 다만 베타 개체 성격 차이가 커서 완전히 안전하다고 보긴 어렵습니다.',
    source: '커뮤니티 관찰',
  },
  {
    a: 'red-belly-piranha-sp',
    b: 'silver-dollar',
    result: 'caution',
    reason:
      '피라냐와 실버달러는 남미에서 실제로 서식지를 공유하는 조합으로, 실버달러의 빠른 유영 속도 덕분에 충분히 큰 수조에서는 종종 함께 사육됩니다. 그래도 위험이 완전히 없는 건 아니라 대형 수조와 충분한 무리가 전제됩니다.',
    source: '도감/커뮤니티',
  },
];

function sqlStr(v) {
  if (v === null || v === undefined) return 'null';
  return `'${String(v).replace(/'/g, "''")}'`;
}

function sqlNum(v) {
  if (v === null || v === undefined) return 'null';
  return String(v);
}

function sqlBool(v) {
  return v ? 'true' : 'false';
}

function sqlTextArray(arr) {
  if (!arr || arr.length === 0) return "'{}'";
  const escaped = arr.map((s) => `"${String(s).replace(/"/g, '\\"')}"`);
  return `'{${escaped.join(',')}}'`;
}

const lines = [];
lines.push('-- Auto-generated by scripts/generate_supabase_seed.mjs from data/species_data.json.');
lines.push('-- Do not edit by hand — edit species_data.json (or the Excel pipeline) and regenerate.');
lines.push('');
lines.push('begin;');
lines.push('');
lines.push('truncate table species_pair_overrides, species, care_groups restart identity cascade;');
lines.push('');

lines.push('insert into care_groups (id, temp_min, temp_max, ph_min, ph_max, tank_min, temperament, diet, feeding, lifespan, water_level, schooling_need, schooling_min_group, difficulty, color, tips, fin_nipper, predatory, same_species_aggression_only, breeding_aggression_only, territorial, water_sensitivity) values');
const groupRows = Object.entries(data.groups).map(([id, g]) => {
  return `  (${sqlStr(id)}, ${sqlNum(g.temp[0])}, ${sqlNum(g.temp[1])}, ${sqlNum(g.ph[0])}, ${sqlNum(g.ph[1])}, ${sqlNum(g.tankMin)}, ${sqlStr(g.temperament)}, ${sqlStr(g.diet)}, ${sqlStr(g.feeding)}, ${sqlStr(g.lifespan)}, ${sqlStr(g.waterLevel)}, ${sqlBool(g.schooling?.need)}, ${sqlNum(g.schooling?.minGroup ?? 1)}, ${sqlStr(g.difficulty)}, ${sqlStr(g.color)}, ${sqlStr(g.tips)}, ${sqlBool(g.finNipper)}, ${sqlBool(g.predatory)}, ${sqlBool(g.sameSpeciesAggressionOnly)}, ${sqlBool(g.breedingAggressionOnly)}, ${sqlBool(g.territorial)}, ${sqlStr(g.waterSensitivity)})`;
});
lines.push(groupRows.join(',\n') + ';');
lines.push('');

lines.push('insert into species (id, group_id, name, name_en, latin, genus, origin, max_size, aliases, note) values');
const speciesRows = data.species.map((s) => {
  return `  (${sqlStr(s.id)}, ${sqlStr(s.groupId)}, ${sqlStr(s.name)}, ${sqlStr(s.nameEn)}, ${sqlStr(s.latin)}, ${sqlStr(s.genus)}, ${sqlStr(s.origin)}, ${sqlNum(s.maxSize)}, ${sqlTextArray(s.aliases)}, ${sqlStr(s.note)})`;
});
lines.push(speciesRows.join(',\n') + ';');
lines.push('');

lines.push('insert into species_pair_overrides (species_a, species_b, result, reason, source) values');
const overrideRows = PAIR_OVERRIDES.map((o) => {
  return `  (${sqlStr(o.a)}, ${sqlStr(o.b)}, ${sqlStr(o.result)}, ${sqlStr(o.reason)}, ${sqlStr(o.source)})`;
});
lines.push(overrideRows.join(',\n') + ';');
lines.push('');
lines.push('commit;');
lines.push('');

const outPath = path.join(root, 'supabase', 'seed', 'species_seed.sql');
writeFileSync(outPath, lines.join('\n'), 'utf-8');
console.log(`Wrote ${outPath}`);
console.log(`  care_groups: ${groupRows.length}`);
console.log(`  species: ${speciesRows.length}`);
console.log(`  species_pair_overrides: ${overrideRows.length}`);
